service: cleanup_unused_security_groups

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:DescribeSecurityGroups
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - ec2:DeleteSecurityGroup
            - lambda:ListFunctions
          Resource: "*" 
        - Effect: Allow
          Action:
            - cloudwatch:PutMetricData
          Resource: "*"

functions:
  cleanupUnusedSecurityGroups:
    handler: handler.cleanupUnusedSecurityGroups
    description: "Removes unused security groups and tracks deletions in CloudWatch"
    events:
      - schedule:
          rate: cron(0 7 ? * 2 *) # Every Monday at 07:00 UTC

package:
  individually: true
